SET (BULLET_DEPS_BUILD_DIR ${OE_CURRENT_DEPS_BUILD_DIR})
SET (BULLET_DEPS_SRC_DIR ${OE_CURRENT_DEPS_DIR}/bullet-2.77)
SET (BULLET_DEPS_INCLUDE_DIR ${OE_CURRENT_DEPS_BUILD_DIR}/include)
SET (BULLET_DEPS_LIB_DIR ${OE_CURRENT_DEPS_BUILD_DIR}/lib)

MESSAGE("INCL: ${BULLET_DEPS_INCLUDE_DIR}")